/**
 * 功能区附魔选项目录：id、展示文案、效果描述、等级（供后续结算与界面用）
 * 等级：green=直接倍率/筹码，blue=花色/点数凑牌型，purple=条件触发高收益，gold=条件触发成长型
 */
import {
  EFFECT_CHIPS_ADD,
  EFFECT_MULT_ADD,
  EFFECT_CARD_SUIT_AS,
  EFFECT_CARD_RANK_AS,
  EFFECT_CONDITION_PLAY_HAS_RANK,
  EFFECT_WHEN_IN_HAND,
  SUIT_AS_RED,
  SUIT_AS_BLACK,
  SUIT_AS_ANY,
  SUIT_AS_MAJORITY_PLAY,
  RANK_AS_FACE,
  RANK_AS_ACE,
  RANK_AS_10,
  RANK_AS_MAX_IN_PLAY,
  RANK_AS_MIN_IN_PLAY,
  RANK_AS_MAX_MINUS_1,
  RANK_AS_SAME_AS_RANDOM_IN_PLAY,
  RANK_AS_ANY_OF_A234,
  RANK_AS_ANY_OF_456,
  RANK_AS_ANY_OF_789,
  RANK_AS_ANY,
  RANK_AS_10_FOR_STRAIGHT,
  EFFECT_CARD_COPY_ANOTHER_IN_PLAY,
  RANK_GROUP_FACE,
  RANK_GROUP_ACE,
  ENCHANT_TIER,
  SUIT_INDEX_SPADE,
  SUIT_INDEX_HEART,
  SUIT_INDEX_DIAMOND,
  SUIT_INDEX_CLUB,
  EFFECT_IF_THIS_CARD_SUIT,
  EFFECT_IF_THIS_CARD_RED_BLACK,
  EFFECT_IF_THIS_CARD_FACE,
  EFFECT_IF_THIS_CARD_ACE,
  EFFECT_IF_THIS_CARD_RANK_EVEN,
  EFFECT_IF_THIS_CARD_RANK_ODD,
  EFFECT_IF_THIS_CARD_RANK_LE5,
  EFFECT_IF_THIS_CARD_RANK_GE10,
  EFFECT_IF_THIS_CARD_PRIME,
  EFFECT_CONDITION_PLAY_HAS_PAIR,
  EFFECT_CONDITION_PLAY_HAS_RED,
  EFFECT_CONDITION_PLAY_HAS_FACE,
  EFFECT_WHEN_IN_HAND_NOT_PLAYED,
  EFFECT_CONDITION_PLAY_ALL_RED,
  EFFECT_CONDITION_PLAY_ALL_BLACK,
  EFFECT_CONDITION_PLAY_ALL_FOUR_SUITS,
  EFFECT_CONDITION_PLAY_NO_SPADE,
  EFFECT_CONDITION_PLAY_HEARTS_MOST,
  EFFECT_CONDITION_PLAY_ALL_RANK_LT7,
  EFFECT_THIS_CARD_SAME_RANK_AS_ANOTHER_IN_HAND,
} from './constants';

/** 所有功能区附魔选项（id、label、effect、tier） */
export const FUNCTION_ENCHANT_CATALOG = [
  // ---------- 绿色：直接或基于单牌/打出条件的倍率/筹码 ----------
  { id: 'chips_5', label: '筹码 +5', effect: { type: EFFECT_CHIPS_ADD, value: 5 }, tier: ENCHANT_TIER.GREEN },
  { id: 'mult_1', label: '倍率 +1', effect: { type: EFFECT_MULT_ADD, value: 1 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_suit_heart_chips15', label: '若这张牌是红心，+15 筹码', effect: { type: EFFECT_IF_THIS_CARD_SUIT, suitIndex: SUIT_INDEX_HEART, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_suit_diamond_chips15', label: '若这张牌是方片，+15 筹码', effect: { type: EFFECT_IF_THIS_CARD_SUIT, suitIndex: SUIT_INDEX_DIAMOND, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_suit_spade_chips15', label: '若这张牌是黑桃，+15 筹码', effect: { type: EFFECT_IF_THIS_CARD_SUIT, suitIndex: SUIT_INDEX_SPADE, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_suit_club_chips15', label: '若这张牌是梅花，+15 筹码', effect: { type: EFFECT_IF_THIS_CARD_SUIT, suitIndex: SUIT_INDEX_CLUB, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_red_mult2', label: '若这张牌是红色花色，+2 倍率', effect: { type: EFFECT_IF_THIS_CARD_RED_BLACK, redOrBlack: 'red', mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_black_mult2', label: '若这张牌是黑色花色，+2 倍率', effect: { type: EFFECT_IF_THIS_CARD_RED_BLACK, redOrBlack: 'black', mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_face_chips20', label: '若这张牌是人头牌(J/Q/K)，+20 筹码', effect: { type: EFFECT_IF_THIS_CARD_FACE, chips: 20 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_ace_mult3', label: '若这张牌是 A，+3 倍率', effect: { type: EFFECT_IF_THIS_CARD_ACE, mult: 3 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_even_chips15', label: '若这张牌的点数是偶数，+15 筹码', effect: { type: EFFECT_IF_THIS_CARD_RANK_EVEN, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_odd_mult2', label: '若这张牌的点数是奇数，+2 倍率', effect: { type: EFFECT_IF_THIS_CARD_RANK_ODD, mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_rank_le5_chips15', label: '若这张牌的点数小于等于 5，+15 筹码', effect: { type: EFFECT_IF_THIS_CARD_RANK_LE5, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_rank_ge10_mult2', label: '若这张牌的点数大于等于 10，+2 倍率', effect: { type: EFFECT_IF_THIS_CARD_RANK_GE10, mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_pair_chips10', label: '若打出的牌型包含对子，+10 筹码', effect: { type: EFFECT_CONDITION_PLAY_HAS_PAIR, chips: 10 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_has_red_chips10', label: '若打出的牌中包含至少一张红色牌，+10 筹码', effect: { type: EFFECT_CONDITION_PLAY_HAS_RED, chips: 10 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_has_face_mult2', label: '若打出的牌中包含至少一张人头牌，+2 倍率', effect: { type: EFFECT_CONDITION_PLAY_HAS_FACE, mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'in_hand_not_played_mult2', label: '若此牌在手牌中未打出，+2 倍率', effect: { type: EFFECT_WHEN_IN_HAND_NOT_PLAYED, mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_all_red_mult3', label: '若打出的牌中所有牌都是红色花色，+3 倍率', effect: { type: EFFECT_CONDITION_PLAY_ALL_RED, mult: 3 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_all_black_chips20', label: '若打出的牌中所有牌都是黑色花色，+20 筹码', effect: { type: EFFECT_CONDITION_PLAY_ALL_BLACK, chips: 20 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_all_four_suits_chips20', label: '若打出的牌中包含所有四种花色，+20 筹码', effect: { type: EFFECT_CONDITION_PLAY_ALL_FOUR_SUITS, chips: 20 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_no_spade_chips15', label: '若打出的牌中不包含任何黑桃，+15 筹码', effect: { type: EFFECT_CONDITION_PLAY_NO_SPADE, chips: 15 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_hearts_most_mult2', label: '若打出的牌中红心的数量最多，+2 倍率', effect: { type: EFFECT_CONDITION_PLAY_HEARTS_MOST, mult: 2 }, tier: ENCHANT_TIER.GREEN },
  { id: 'if_prime_chips20', label: '若这张牌的点数是质数(2/3/5/7)，+20 筹码', effect: { type: EFFECT_IF_THIS_CARD_PRIME, chips: 20 }, tier: ENCHANT_TIER.GREEN },
  { id: 'cond_play_all_rank_lt7_chips25', label: '若打出的牌中所有牌的点数都小于 7，+25 筹码', effect: { type: EFFECT_CONDITION_PLAY_ALL_RANK_LT7, chips: 25 }, tier: ENCHANT_TIER.GREEN },
  { id: 'same_rank_as_another_mult2', label: '这张牌的点数与手牌中另一张牌相同时，+2 倍率', effect: { type: EFFECT_THIS_CARD_SAME_RANK_AS_ANOTHER_IN_HAND, mult: 2 }, tier: ENCHANT_TIER.GREEN },

  // ---------- 蓝色：花色/点数变化，凑牌型 ----------
  { id: 'suit_heart', label: '这张牌被视为红心', effect: { type: EFFECT_CARD_SUIT_AS, suitIndex: SUIT_INDEX_HEART }, tier: ENCHANT_TIER.BLUE },
  { id: 'suit_spade', label: '这张牌被视为黑桃', effect: { type: EFFECT_CARD_SUIT_AS, suitIndex: SUIT_INDEX_SPADE }, tier: ENCHANT_TIER.BLUE },
  { id: 'suit_red', label: '这张牌可以被视为任意红色花色（红心或方片）', effect: { type: EFFECT_CARD_SUIT_AS, value: SUIT_AS_RED }, tier: ENCHANT_TIER.BLUE },
  { id: 'suit_black', label: '这张牌可以被视为任意黑色花色（黑桃或梅花）', effect: { type: EFFECT_CARD_SUIT_AS, value: SUIT_AS_BLACK }, tier: ENCHANT_TIER.BLUE },
  { id: 'suit_any', label: '这张牌可以被视为任意花色', effect: { type: EFFECT_CARD_SUIT_AS, value: SUIT_AS_ANY }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_ace', label: '这张牌的点数被视为 A', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_ACE }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_10', label: '这张牌的点数被视为 10', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_10 }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_max_minus_1', label: '这张牌的点数被视为比打出牌中点数最高的牌小 1', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_MAX_MINUS_1 }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_same_as_random_play', label: '这张牌的点数被视为与打出牌中另一张随机牌的点数相同', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_SAME_AS_RANDOM_IN_PLAY }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_any_of_A234', label: '这张牌的点数可以被视为 A、2、3、4 中的任意一个', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_ANY_OF_A234 }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_any_of_456', label: '这张牌的点数可以被视为 4、5、6 中的任意一个', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_ANY_OF_456 }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_any_of_789', label: '这张牌的点数可以被视为 7、8、9 中的任意一个', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_ANY_OF_789 }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_face', label: '这张牌的点数可以被视为 J、Q、K 中的任意一个', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_FACE }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_any', label: '这张牌可以被视为任意点数', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_ANY }, tier: ENCHANT_TIER.BLUE },
  { id: 'card_copy_another', label: '打出时，这张牌完全复制打出牌中另一张牌的点数和花色', effect: { type: EFFECT_CARD_COPY_ANOTHER_IN_PLAY }, tier: ENCHANT_TIER.BLUE },
  { id: 'suit_majority_play', label: '这张牌的花色视为打出牌中数量最多的花色', effect: { type: EFFECT_CARD_SUIT_AS, value: SUIT_AS_MAJORITY_PLAY }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_max_play', label: '这张牌的点数视为你打出牌中点数最高的牌', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_MAX_IN_PLAY }, tier: ENCHANT_TIER.BLUE },
  { id: 'rank_min_play', label: '这张牌的点数视为你打出牌中点数最低的牌', effect: { type: EFFECT_CARD_RANK_AS, value: RANK_AS_MIN_IN_PLAY }, tier: ENCHANT_TIER.BLUE },

  // ---------- 紫色：条件触发的高倍率/筹码 ----------
  {
    id: 'mult_1_same_suit',
    label: '+1 倍率，若手牌中有同花色则再 +1',
    effect: { type: EFFECT_MULT_ADD, value: 1, extraIfSameSuitInHand: 1 },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'cond_q_mult5',
    label: '若打出的手牌中至少有一张 Q，倍率 +5',
    effect: { type: EFFECT_CONDITION_PLAY_HAS_RANK, rank: 'Q', then: { type: EFFECT_MULT_ADD, value: 5 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'cond_k_chips30',
    label: '若打出的手牌中至少有一张 K，筹码 +30',
    effect: { type: EFFECT_CONDITION_PLAY_HAS_RANK, rank: 'K', then: { type: EFFECT_CHIPS_ADD, value: 30 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'cond_a_mult2',
    label: '若打出的手牌中至少有一张 A，倍率 +2',
    effect: { type: EFFECT_CONDITION_PLAY_HAS_RANK, rank: 'A', then: { type: EFFECT_MULT_ADD, value: 2 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'cond_flush_mult3',
    label: '若打出的手牌为同花，倍率 +3',
    effect: { type: 'condition_play_is_flush', then: { type: EFFECT_MULT_ADD, value: 3 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'cond_straight_chips50',
    label: '若打出的手牌为顺子，筹码 +50',
    effect: { type: 'condition_play_is_straight', then: { type: EFFECT_CHIPS_ADD, value: 50 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'cond_pair_same_rank_mult4',
    label: '当这张牌被打出时，若本手牌中有另一张同点数牌，倍率 +4',
    effect: { type: 'condition_play_has_pair_with_this', then: { type: EFFECT_MULT_ADD, value: 4 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'no_pair_chips25',
    label: '打出包含这张牌的一手牌时，若其中没有对子/三条/四条，筹码 +25',
    effect: { type: 'condition_play_no_pair', then: { type: EFFECT_CHIPS_ADD, value: 25 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'three_same_suit_chips40',
    label: '若本手牌中有至少 3 张同花色，这张牌筹码 +40',
    effect: { type: 'condition_hand_has_3_same_suit', then: { type: EFFECT_CHIPS_ADD, value: 40 } },
    tier: ENCHANT_TIER.PURPLE,
  },
  {
    id: 'two_same_rank_mult2',
    label: '若本手牌中有至少 2 张同点数，这张牌倍率 +2',
    effect: { type: 'condition_hand_has_pair', then: { type: EFFECT_MULT_ADD, value: 2 } },
    tier: ENCHANT_TIER.PURPLE,
  },

  // ---------- 金色：条件触发的成长型 ----------
  {
    id: 'in_hand_face_chips20',
    label: '当这张牌在手牌中时，所有人头牌筹码 +20',
    effect: { type: EFFECT_WHEN_IN_HAND, then: { type: 'chips_add_for_rank_group', rankGroup: RANK_GROUP_FACE, value: 20 } },
    tier: ENCHANT_TIER.GOLD,
  },
  {
    id: 'in_hand_ace_chips15',
    label: '当这张牌在手牌中时，所有 A 筹码 +15',
    effect: { type: EFFECT_WHEN_IN_HAND, then: { type: 'chips_add_for_rank_group', rankGroup: RANK_GROUP_ACE, value: 15 } },
    tier: ENCHANT_TIER.GOLD,
  },
  {
    id: 'discard_draw1',
    label: '弃掉这张牌时，从抽牌堆额外抽 1 张牌',
    effect: { type: 'on_discard_draw', count: 1 },
    tier: ENCHANT_TIER.GOLD,
  },
];
